[build]
  command = "npm run prerender"
  functions = "./functions"
  publish = "dist/frontend/browser"
[dev]
  command = "npm run start"
  functions = "./functions"
  publish = "src"
[functions]
  node_bundler = "esbuild"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
